site_name: iiif-prezi3

nav:
    - 'README': README.md
    - 'Getting started':
        - 'Using iiifprezi3 without helper methods': 'getting-started-using-iiifprezi3-without-helpermethods.md'
    - Technical:
        - 'generate-schema.md'
        - 'write-helper-method.md'
        - code.md
    - Cookbook Recipes:
        - ... | flat | recipes/*.md

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_submodules: true
