name: docs
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip-docs
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.dev.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e '.[docs]'

      # build docs in strict mode as a check for pull requests
      - name: Build docs (strict mode)
        if: ${{ github.event_name == 'pull_request' }}
        run: mkdocs build --strict

      # build docs and publish on push to main
      - name: Deploy docs
        if: ${{ github.event_name == 'push' }}
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml